StayFit/Models/ServiceBooking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace StayFit.Models
{
    public class ServiceBooking
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Booking_Id { get; set; }


        [Required]
        [Display(Name = "Choose a Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime BookingDate { get; set; }

        [Required]
        public Boolean BookingStatus { get; set; }
        

        [Required]
        public virtual ApplicationUser ApplicationUser { get; set; }

        [Required]
        [Display(Name = "Choose a Service")]
        public virtual Service Service { get; set; }

        
        [Display(Name = "Choose a Prefered Time Schedule")]
        public virtual ServiceTimings ServiceTimings { get; set; }
    }
}

StayFit/Controllers/ServiceBookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StayFit.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using StayFit.Common;

namespace StayFit.Controllers
{
    [Authorize]
    public class ServiceBookingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ServiceBookings
        [Authorize]
        public ActionResult Index()
        {
            string id = User.Identity.GetUserId();
            GymMember memberProfile = db.GymMember.Where(p => p.ApplicationUser.Id == id).FirstOrDefault();
            if (memberProfile == null)
            {
                string name = User.Identity.Name;
                if (name.Equals("admin@admin.com"))
                { return RedirectToAction("GymMembersList", "Admin"); }
                else { return RedirectToAction("Create", "GymMembers"); }
                //return HttpNotFound();
                
            }
            var user = db.Users.Find(User.Identity.GetUserId());
            var serviceBookings = db.ServiceBooking.Where(m => m.ApplicationUser.Id == user.Id).ToList();
            return View(serviceBookings);
        }

        // GET: ServiceBookings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceBooking serviceBooking = db.ServiceBooking.Find(id);
            if (serviceBooking == null)
            {
                return HttpNotFound();
            }
            return View(serviceBooking);
        }

        
        public ActionResult CancelBooking(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceBooking serviceBooking = db.ServiceBooking.Find(id);
            if (serviceBooking == null)
            {
                return HttpNotFound();
            }
            serviceBooking.BookingStatus = false;
            if (ModelState.IsValid)
            {
                db.Entry(serviceBooking).State = EntityState.Modified;
                db.SaveChanges();
                String toEmail = serviceBooking.ApplicationUser.Email;
                String subject = serviceBooking.Service.SeviceName + " Booking  Cancellation Details";
                //String contents = newsletterViewModel.News_content;
                String contents1 = String.Empty;
                using (StreamReader reader = new StreamReader(Server.MapPath("~/Email_Template/Cancel_Contents.html")))
                {
                    contents1 = reader.ReadToEnd();
                }
                contents1 = contents1.Replace("CONTENT0", serviceBooking.Booking_Id.ToString());
                contents1 = contents1.Replace("CONTENT1", serviceBooking.Service.SeviceName);
                contents1 = contents1.Replace("CONTENT2", serviceBooking.BookingDate.ToShortDateString());
                contents1 = contents1.Replace("CONTENT3", serviceBooking.ServiceTimings.Timing);
                //contents = contents1 + contents ;
                EmailSender es = new EmailSender();
                es.Send(toEmail, subject, contents1);
                return RedirectToAction("Index");
            }
            return View(serviceBooking);
        }
        // GET: ServiceBookings/Create
        public ActionResult Create()
        {
            ViewBag.Service = new SelectList(db.Service, "Service_Id ", "SeviceName");
            return View();
        }

        public JsonResult GetTimings(int timing_id)
        {

            List<ServiceTimings> ServiceTimings = db.ServiceTimings.Where(x => x.Service.Service_Id == timing_id).ToList();
            return Json(ServiceTimings, JsonRequestBehavior.AllowGet);
        }

        // POST: ServiceBookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Booking_Id,BookingDate,BookingStatus,Service,ServiceTimings")] ServiceBooking serviceBooking)
        {
            // int s_Id = serviceBooking.Service.Service_Id;
            // int t_Id = serviceBooking.ServiceTimings.Timing_Id;


           serviceBooking.BookingStatus = true;
           Service service  = db.Service.Where(x => x.Service_Id == serviceBooking.Service.Service_Id).SingleOrDefault();

           ServiceTimings Timings = db.ServiceTimings.Where(x => x.Timing_Id == serviceBooking.ServiceTimings.Timing_Id).SingleOrDefault();

           serviceBooking.Service = db.Service.Where(x => x.Service_Id == serviceBooking.Service.Service_Id).SingleOrDefault();
           serviceBooking.ServiceTimings = db.ServiceTimings.Where(x => x.Timing_Id == serviceBooking.ServiceTimings.Timing_Id).SingleOrDefault();

           serviceBooking.ApplicationUser = db.Users.Find(User.Identity.GetUserId());
           serviceBooking.Service.SeviceName = service.SeviceName;
           serviceBooking.Service.ServiceDesc = service.ServiceDesc;
           serviceBooking.Service.Service_Id = service.Service_Id;
           serviceBooking.ServiceTimings.Timing_Id = Timings.Timing_Id;
           serviceBooking.ServiceTimings.Timing = Timings.Timing;
           serviceBooking.ServiceTimings.Service = Timings.Service;

            ModelState.Clear();
            TryValidateModel(serviceBooking);




            if (ModelState.IsValid)
            {
                serviceBooking.ApplicationUser = db.Users.Find(User.Identity.GetUserId());
                db.ServiceBooking.Add(serviceBooking);
                db.SaveChanges();
                String toEmail = serviceBooking.ApplicationUser.Email;
                String subject = serviceBooking.Service.SeviceName + " Booking Details";
                //String contents = newsletterViewModel.News_content;
                String contents1 = String.Empty;
                using (StreamReader reader = new StreamReader(Server.MapPath("~/Email_Template/Booking_Contents.html")))
                {
                    contents1 = reader.ReadToEnd();
                }
                contents1 = contents1.Replace("CONTENT0", serviceBooking.Booking_Id.ToString());
                contents1 = contents1.Replace("CONTENT1", serviceBooking.Service.SeviceName);
                contents1 = contents1.Replace("CONTENT2", serviceBooking.BookingDate.ToShortDateString());
                contents1 = contents1.Replace("CONTENT3", serviceBooking.ServiceTimings.Timing);
                //contents = contents1 + contents ;
                EmailSender es = new EmailSender();
                es.Send(toEmail, subject, contents1);
                return RedirectToAction("Index");
            }
            ViewBag.Service = new SelectList(db.Service, "Service_Id ", "SeviceName");
            return View(serviceBooking);
        }

        // GET: ServiceBookings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceBooking serviceBooking = db.ServiceBooking.Find(id);
            if (serviceBooking == null)
            {
                return HttpNotFound();
            }
            return View(serviceBooking);
        }

        // POST: ServiceBookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Booking_Id,BookingDate,BookingStatus")] ServiceBooking serviceBooking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serviceBooking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serviceBooking);
        }

        // GET: ServiceBookings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceBooking serviceBooking = db.ServiceBooking.Find(id);
            if (serviceBooking == null)
            {
                return HttpNotFound();
            }
            return View(serviceBooking);
        }

        // POST: ServiceBookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceBooking serviceBooking = db.ServiceBooking.Find(id);
            db.ServiceBooking.Remove(serviceBooking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StayFit/Views/ServiceBookings/Create.cshtml
@model StayFit.Models.ServiceBooking

@{
   ViewBag.Title = "Create";
   Layout = "~/Views/Shared/Gym_Member_Layout.cshtml";
}
<div class="well">
    <h1 style="font-size:45px;font-weight:500;font-style:initial;font-family:Georgia; color:darkcyan">Service Booking</h1>
    <link rel="stylesheet" type="text/css" media="all" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css" />
    <hr style="border-top: 1px solid #ccc; background: transparent;">
    <div class="row">

        <div class="col-md-6">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="container" style="margin-left:20px">
                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            <h3 style="font-size:21px; font-weight:400;font-family:Helvetica; color:darkcyan;">Choose the Service: </h3>
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Service.Service_Id, (IEnumerable<SelectListItem>)ViewBag.Service, "--Select a service--", new { @class = "form-control", @id = "xx" })

                            </div>
                        </div>

                        <div class="form-group">
                            <h3 style="font-size:21px; font-weight:400;font-family:Helvetica; color:darkcyan; display:inline-block">Choose the schedule: </h3>
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.ServiceTimings.Timing_Id, new SelectList(" "), "--Select a service timing--", new { @class = "form-control", @id = "yy" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <h3 style="font-size:21px; font-weight:400;font-family:Helvetica; color:darkcyan; display:inline-block">Choose the Date: </h3>
                                @Html.EditorFor(model => model.BookingDate, new { htmlAttributes = new { @class = "form-control date-picker2 " } })
                                @Html.ValidationMessageFor(model => model.BookingDate, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group text-center">
                            <div class="col-md-2">
                                <input type="submit" value="Book" class="btn btn-success" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="col-md-6">
            <img src="~/Content/Images/ser2.png" class="img-responsive img-rounded" />

        </div>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script>

        $(document).ready(function () {
            $("#xx").change(function () {
                var item = this;
                $.get("/ServiceBookings/GetTimings", { Timing_Id: item.value }, function (data) {
                    $("#yy").empty();
                    $.each(data, function (index, row) {
                        $("#yy").append("<option value='" + row.Timing_Id + "'>" + row.Timing + "</option>")

                    });
                });
            })
        });
    </script>

</div>

StayFit/Views/ServiceBookings/Delete.cshtml
@model StayFit.Models.ServiceBooking

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Gym_Member_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ServiceBooking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BookingDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookingDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BookingStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookingStatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Users List", "GymMembersList")
        </div>
    }
</div>

StayFit/Views/ServiceBookings/Details.cshtml
@model StayFit.Models.ServiceBooking

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Gym_Member_Layout.cshtml";
}
<style>
    img:hover {
        -webkit-transform: scaleX(-1);
        transform: scaleX(-1);
    }
</style>
<div class="container well">

    <h1 style="font-size:45px;font-weight:500;font-style:initial;font-family:Georgia; color:#18bc9c">Service Booking Details</h1>
    <hr style="border-top: 1px solid #ccc; background: transparent;">
    @if (Model.BookingStatus == true)
    {
        <div class="row">

            <div class="col-md-6">
                @if (Model.Service.Service_Id == 1)
                {
                    <img src="~/Content/Images/yoga2.png" class="img-responsive img-rounded " />
                }
                @if (Model.Service.Service_Id == 2)
                {
                    <img src="~/Content/Images/boxing.png" class="img-responsive img-rounded " />
                }
                @if (Model.Service.Service_Id == 3)
                {
                    <img src="~/Content/Images/cardio4.png" class="img-responsive img-rounded " />
                }
                @if (Model.Service.Service_Id == 4)
                {
                    <img src="~/Content/Images/bodypump.png" class="img-responsive img-rounded " />
                }
                @if (Model.Service.Service_Id == 5)
                {
                    <img src="~/Content/Images/zumba5.png" class="img-responsive img-rounded " />
                }
                @if (Model.Service.Service_Id == 6)
                {
                    <img src="~/Content/Images/crsfit1.png" class="img-responsive img-rounded " />
                }
            </div>
            <div class="col-md-6">
                <div><h3 style="font-size:25px; font-weight:400;font-family:Helvetica; color:#18bc9c; display:inline-block">Booking Id:  </h3> <h3 style="font-size:25px; font-weight:400;font-family:Calibri; display:inline-block">  @Html.DisplayFor(model => model.Booking_Id) </h3></div>

                <h3 style="font-size:25px; font-weight:400;font-family:Helvetica; color:#18bc9c; display:inline-block">Service Booked:  </h3> <h3 style="font-size:25px; font-weight:400;font-family:Calibri; display:inline-block">  @Html.DisplayFor(model => model.Service.SeviceName)</h3>
                <h4 style="font-size:20px; font-weight:100; font-family:Calibri"> @Html.DisplayFor(model => model.Service.ServiceDesc)</h4>
                <h3 style="font-size:25px; font-weight:400;font-family:Helvetica; color:#18bc9c; display:block">Scheduled On:</h3>
                <ul>
                    <li><h4 style="font-size:20px;color:#18bc9c; display:inline-block">Booking Date:  </h4>   <h4 style="font-size:20px; font-weight:400; font-family:Calibri; display:inline-block">  @Html.DisplayFor(model => model.BookingDate) </h4></li>
                    <li><h4 style="font-size:20px;color:#18bc9c; display:inline-block">Timing:  </h4>   <h4 style="font-size:20px; font-weight:400; font-family:Calibri;display:inline-block">  @Html.DisplayFor(model => model.ServiceTimings.Timing) </h4></li>
                </ul>


                <div class="text-center">
                    @Html.ActionLink("Cancel Booking", "CancelBooking", "ServiceBookings" , new { confirm = true, id = Model.Booking_Id }, new { @class = "btn btn-danger hover mt-20", @OnClick = "return confirm('Do You Wanna Cancel The Booking? {Press Ok to Confirm}');" })
                </div>
            </div>
        </div>
    }
    else
    {
        <div>
            <h3 style="font-size:25px; font-weight:400;font-family:Helvetica; color:darkcyan; display:inline-block">Booking is  been cancelled!!!!</h3>
        </div>
        <hr />
        <h4 style="font-size:20px; font-weight:400;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
            <span> <i class="glyphicon glyphicon-hand-right" style="color:darkcyan"></i> </span> @Html.ActionLink("Book New a Service", "Create")<span> <i class="glyphicon glyphicon-hand-right" style="color:darkcyan"></i> </span>
        </h4>
    }

    <script type="text/javascript">
        $(document).ready(function () {
            $("input[name='deleteall']").click(function () {
                return confirm('Delete all selected elements?');
            });
        });
    </script>
</div>

StayFit/Views/ServiceBookings/Edit.cshtml
@model StayFit.Models.ServiceBooking

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Gym_Member_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ServiceBooking</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Booking_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BookingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookingStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.BookingStatus)
                    @Html.ValidationMessageFor(model => model.BookingStatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StayFit/Views/ServiceBookings/Index.cshtml
@model IEnumerable<StayFit.Models.ServiceBooking>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Gym_Member_Layout.cshtml";
}

<div class="well">
    <h1 style="font-size:45px;font-weight:500;font-style:initial;font-family:Georgia; color:#18bc9c"> Your Bookings</h1>
    <hr style="border-top: 1px solid #ccc; background: transparent;">
    <br />

    <table class="table table-striped table-responsive table-hover">
        <thead class="thead-light">
            <tr style="background-color:#18bc9c;height:20px">
                <th>
                    Booking Id
                </th>
                <th>
                    Service Choosen
                </th>
                <th>
                    Booking Date
                </th>
                <th>
                    Scheduled Time
                </th>
                <th>
                    Booking Status
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Booking_Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Service.SeviceName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookingDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ServiceTimings.Timing)
                    </td>
                    <td>
                        @if (item.BookingStatus == true)
                        {<p>Active</p> }
                        else
                        { <p style="color:brown">Cancelled</p>}

                    </td>
                    <td>
                        @Html.ActionLink("View Details", "Details", new { id = item.Booking_Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts {
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.js")
    @Scripts.Render("~/Scripts/DataTables/dataTables.bootstrap.js")
    <script>
$(document).ready(function () {
$('.table').DataTable();
});
    </script>
}
<link href="~/Content/DataTables/css/dataTables.bootstrap.min.css"
      rel="stylesheet" />