StayFit/Controllers/GymMembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StayFit.Models;
using StayFit.Common;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System.IO;

namespace StayFit.Controllers
{   [Authorize]
    public class GymMembersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

      
        
        // GET: GymMembers
        public ActionResult Index()
        {
            string id = User.Identity.GetUserId();
            GymMember memberProfile = db.GymMember.Where(p => p.ApplicationUser.Id == id).FirstOrDefault();
            if (memberProfile == null)
            {
                string name = User.Identity.Name;
                if (name.Equals("admin@admin.com"))
                { return RedirectToAction("GymMembersList", "Admin"); }
                else{ return RedirectToAction("Create"); }
            }
            return View();
        }

       

        // GET: GymMembers/UserProfile/
        public ActionResult UserProfile()
        {
            string id = User.Identity.GetUserId();
            if (id == null)
            {
               return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            GymMember memberProfile = db.GymMember.Where(p => p.ApplicationUser.Id == id).FirstOrDefault();
            if (memberProfile == null)
            {
                string name = User.Identity.Name;
                if (name.Equals("admin@admin.com"))
                { return RedirectToAction("GymMembersList", "Admin"); }
                else { return RedirectToAction("Create"); }
            }
            return View(memberProfile);
        }

        // GET: GymMembers/Create
        public ActionResult Create()
        {
            ViewBag.MembershipType = new SelectList(db.MembershipType, "Membership_Id", "Membership_tier");
            return View();
        }

        // POST: GymMembers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Member_Id,FirstName,LastName,DateOfBirth,Address,Height,Weight,MembershipType")] GymMember gymMember)
        {
            gymMember.ApplicationUser = db.Users.Find(User.Identity.GetUserId());
            ModelState.Clear();
            TryValidateModel(gymMember);
            if (ModelState.IsValid)
            {
                gymMember.ApplicationUser = db.Users.Find(User.Identity.GetUserId());
                
                db.GymMember.Add(gymMember);
                db.SaveChanges();
                String toEmail = gymMember.ApplicationUser.Email;
                String subject = "StayFit Registeration Confirmation";
                String contents = String.Empty;
                using (StreamReader reader = new StreamReader(Server.MapPath("~/Email_Template/Email_Contents.html")))
                {
                    contents = reader.ReadToEnd();
                }
                
                EmailSender es = new EmailSender();
                es.Send(toEmail, subject, contents);
                return RedirectToAction("Index");
            }
            ViewBag.MembershipType = new SelectList(db.MembershipType, "Membership_Id", "Membership_tier");
            return View(gymMember);
        }

        


        // GET: GymMembers/Edit/5
        public ActionResult Edit(int? id)
        {

            ViewBag.MembershipType = new SelectList(db.MembershipType, "Membership_Id", "Membership_tier");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GymMember gymMember = db.GymMember.Find(id);
            if (gymMember == null)
            {
                return HttpNotFound();
            }
            return View(gymMember);
        }

        // POST: GymMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Member_Id,FirstName,LastName,DateOfBirth,Address,Height,Weight,MembershipType")] GymMember gymMember)
        {
            gymMember.ApplicationUser = db.Users.Find(User.Identity.GetUserId());
            ModelState.Clear();
            TryValidateModel(gymMember);

            if (ModelState.IsValid)
            {
                db.Entry(gymMember).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MembershipType = new SelectList(db.MembershipType, "Membership_Id", "Membership_tier");
            return View(gymMember);
        }

        /// <summary>  
        /// Validate Captcha  
        /// </summary>  
        /// <param name="response"></param>  
        /// <returns></returns>  
        public static CaptchaResponse ValidateCaptcha(string response)
        {
            string secret = System.Web.Configuration.WebConfigurationManager.AppSettings["recaptchaPrivateKey"];
            var client = new WebClient();
            var jsonResult = client.DownloadString(string.Format("https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}", secret, response));
            return JsonConvert.DeserializeObject<CaptchaResponse>(jsonResult.ToString());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        // GET: Posts list
        public ActionResult MemberPostsList()
        {
            string id = User.Identity.GetUserId();
            GymMember memberProfile = db.GymMember.Where(p => p.ApplicationUser.Id == id).FirstOrDefault();
            if (memberProfile == null)
            {
                string name = User.Identity.Name;
                if (name.Equals("admin@admin.com"))
                { return RedirectToAction("GymMembersList", "Admin"); }
                else { return RedirectToAction("Create"); }
            }
            return View(db.Posts.ToList());
        }


        // GET: PostMessages/Details/5
        
        public ActionResult MemberPostDetails(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            PostMessageDetailsViewModel postMessageDetailsViewModel = new PostMessageDetailsViewModel();
            var postMessage = db.PostMessages.Where(m => m.Post.Post_Id == id).ToList();
            postMessageDetailsViewModel.postMessages = postMessage;
            postMessageDetailsViewModel.post_id = post.Post_Id;
            if (postMessageDetailsViewModel == null)
            {
                return HttpNotFound();
            }
            return View(postMessageDetailsViewModel);
        }


        // POST: Posts/Detials
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult MemberPostDetails([Bind(Include = "post_message")] PostMessageDetailsViewModel postMessageDetailsViewModel,string btn, HttpPostedFileBase postedFile)
        {
            CaptchaResponse response = ValidateCaptcha(Request["g-recaptcha-response"]);
            if (response.Success)
            {
                var myUniqueFileName = string.Format(@"{0}", Guid.NewGuid());
               
                if (ModelState.IsValid)
                {
                    int post_id = Convert.ToInt32(btn);
                    PostMessage postMessage = new PostMessage();
                    Image image = new Image();
                    postMessage.ApplicationUser = db.Users.Find(User.Identity.GetUserId());
                    postMessage.Post_Message = postMessageDetailsViewModel.post_message;
                    Post post = db.Posts.Find(post_id);
                    postMessage.Post = post;
                    if (postedFile != null)
                    {
                        image.Image_Path = myUniqueFileName;
                        string serverPath = Server.MapPath("~/Uploads/");
                        string fileExtension = Path.GetExtension(postedFile.FileName);
                        string filePath = image.Image_Path + fileExtension;
                        image.Image_Path = filePath;
                        postedFile.SaveAs(serverPath + image.Image_Path);
                        db.Images.Add(image);
                        db.SaveChanges();
                        postMessage.Image = image;
                    }
                    
                    
                    db.PostMessages.Add(postMessage);
                    db.SaveChanges();
                    return RedirectToAction("MemberPostDetails");
                }
                else { return View(postMessageDetailsViewModel); }
            }
            else
            {
                return Content("Error From Google ReCaptcha : " + response.ErrorMessage[0].ToString());
            }
        }




        // GET: Posts/DeletePostMessage/5
        public ActionResult DeletePostMessage(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

StayFit/Views/Shared/Admin_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StayFit</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/Style.css" rel="stylesheet" />
    <script src="~/Scripts/tinymce/tinymce.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("GymMembersList", "Admin")" class="navbar-brand">
                    <img src="~/Content/Images/newlogo.png" title="title" alt="additional title" width="110" height="40" style="padding-bottom:8px;" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Gym Members", "GymMembersList", "Admin")</li>
                    <li>@Html.ActionLink("Discussion Board", "PostsList", "Admin")</li>
                    <li>@Html.ActionLink("Newsletter", "Newsletter", "Admin")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

        <footer id="fh5co-footer" class="fh5co-bg" role="contentinfo">
            <div class="overlay"></div>
            <div class="container">
                <div class="row row-pb-md">
                    <div class="col-md-6 fh5co-widget">
                        <h3>About Us.</h3>
                        <p>We are the best of best. We train with confidences. We have designed our gyms around the things that matter most to our members, which allows us to provide high quality gym memberships for low prices.</p>

                        <br />
                    </div>
                    <div class="col-md-6">
                        <h3>Our Classes</h3>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <ul class="fh5co-footer-links">
                                <li><a href="#">Cardio</a></li>
                                <li><a href="#">Yoga</a></li>

                            </ul>
                        </div>

                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <ul class="fh5co-footer-links">
                                <li><a href="#">Cross Fit</a></li>
                                <li><a href="#">Personal Training</a></li>

                            </ul>
                        </div>

                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <ul class="fh5co-footer-links">
                                <li><a href="#">BodyPump</a></li>
                                <li><a href="#">Boxing</a></li>

                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row copyright">
                    <div class="col-md-12 text-center">
                        <p>
                            <small class="block">&copy; 2018 . All Rights Reserved.</small>
                            <small class="block">Designed by Sharuq. Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash</a></small>
                        </p>

                    </div>
                </div>

            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>



    <script>
        $(function () {
            $('.date-picker2').datepicker({
                changeMonth: true,
                changeYear: true,
                minDate: 'today'
            });
        });
    </script>


</body>
</html>

StayFit/Views/Shared/Gym_Member_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StayFit</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/Style.css" rel="stylesheet" />

    <script src="~/Scripts/tinymce/tinymce.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "GymMembers")" class="navbar-brand">
                    <img src="~/Content/Images/newlogo.png" title="title" alt="additional title" width="110" height="40" style="padding-bottom:8px;" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Services", "Index", "GymMembers", null, null, "service", new { id = "service" }, null)</li>
                    <li>@Html.ActionLink("Bookings", "Index", "ServiceBookings")</li>
                    <li>@Html.ActionLink("Discussion Board", "MemberPostsList", "GymMembers")</li>
                    <li>@Html.ActionLink("Profile", "UserProfile", "GymMembers")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />

        <footer id="fh5co-footer" class="fh5co-bg" role="contentinfo">
            <div class="overlay"></div>
            <div class="container">
                <div class="row row-pb-md">
                    <div class="col-md-6 fh5co-widget">
                        <h3>About Us.</h3>
                        <p>We are the best of best. We train with confidences. We have designed our gyms around the things that matter most to our members, which allows us to provide high quality gym memberships for low prices.</p>

                        <br />
                    </div>
                    <div class="col-md-6">
                        <h3>Our Classes</h3>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <ul class="fh5co-footer-links">
                                <li><a href="#">Cardio</a></li>
                                <li><a href="#">Yoga</a></li>

                            </ul>
                        </div>

                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <ul class="fh5co-footer-links">
                                <li><a href="#">Cross Fit</a></li>
                                <li><a href="#">Personal Training</a></li>

                            </ul>
                        </div>

                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <ul class="fh5co-footer-links">
                                <li><a href="#">BodyPump</a></li>
                                <li><a href="#">Boxing</a></li>

                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row copyright">
                    <div class="col-md-12 text-center">
                        <p>
                            <small class="block">&copy; 2018 . All Rights Reserved.</small>
                            <small class="block">Designed by Sharuq. Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash</a></small>
                        </p>

                    </div>
                </div>

            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <script>
        $(function () {
            $('.date-picker').datepicker({
                changeMonth: true,
                changeYear: true,
                maxDate: new Date(2001, 0, 1)
            });
        });
    </script>

    <script>
        $(function () {
            $('.date-picker2').datepicker({
                changeMonth: true,
                changeYear: true,
                minDate: 'today'
            });
        });
    </script>
    
</body>
</html>

StayFit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StayFit</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Style.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <img src="~/Content/Images/newlogo.png" title="title" alt="additional title" width="110" height="40" style="padding-bottom:8px;"/>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Pricing", "Index", "Home", null, null, "pricing", new { id = "pricing" }, null)</li>
                    <li><a href="#fh5co-footer">About Us</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
     @RenderBody()
        <hr />

        <footer id="fh5co-footer" class="fh5co-bg" role="contentinfo">
            <div class="overlay"></div>
            <div class="container" id="fh5co-footer1">
                <div class="row row-pb-md">
                    <div class="col-md-6 fh5co-widget">
                        <h3>About Us.</h3>
                        <p>We are the best of best. We train with confidences. We have designed our gyms around the things that matter most to our members, which allows us to provide high quality gym memberships for low prices.</p>
                        <br />
                        @Html.ActionLink("Become A Member", "Register", "Account", null, new { @class = "btn btn-primary hover mt-20 " })
                    </div>
                    <div class="col-md-6">
                        <h3>Our Classes</h3>
                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <ul class="fh5co-footer-links">
                                <li><a href="#">Cardio</a></li>
                                <li><a href="#">Yoga</a></li>

                            </ul>
                        </div>

                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <ul class="fh5co-footer-links">
                                <li><a href="#">Cross Fit</a></li>
                                <li><a href="#">Personal Training</a></li>

                            </ul>
                        </div>

                        <div class="col-md-4 col-sm-4 col-xs-6">
                            <ul class="fh5co-footer-links">
                                <li><a href="#">BodyPump</a></li>
                                <li><a href="#">Boxing</a></li>

                            </ul>
                        </div>
                    </div>
                </div>

                <div class="row copyright">
                    <div class="col-md-12 text-center">
                        <p>
                            <small class="block">&copy; 2018 . All Rights Reserved.</small>
                            <small class="block">Designed by Sharuq. Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash and Kisspng </a></small>
                        </p>

                    </div>
                </div>

            </div>
        </footer>
   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
   
</body>
</html>